source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'bootstrap-sass', '~> 3.3.5.1'
gem "paperclip", "~> 4.3"
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'simple_form', '~> 3.1.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc


group :development, :test do
 
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

gem 'rails_admin'
gem 'devise'
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'cocoon', '~> 1.2.6'
gem 'rails-i18n'